/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as PluginPluginIdRouteImport } from './routes/plugin.$pluginId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginPluginIdRoute = PluginPluginIdRouteImport.update({
  id: '/plugin/$pluginId',
  path: '/plugin/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/plugin/$pluginId': typeof PluginPluginIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/plugin/$pluginId': typeof PluginPluginIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/plugin/$pluginId': typeof PluginPluginIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/catalog' | '/login' | '/manage' | '/plugin/$pluginId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/catalog' | '/login' | '/manage' | '/plugin/$pluginId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/manage'
    | '/plugin/$pluginId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  LoginRoute: typeof LoginRoute
  ManageRoute: typeof ManageRoute
  PluginPluginIdRoute: typeof PluginPluginIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugin/$pluginId': {
      id: '/plugin/$pluginId'
      path: '/plugin/$pluginId'
      fullPath: '/plugin/$pluginId'
      preLoaderRoute: typeof PluginPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  LoginRoute: LoginRoute,
  ManageRoute: ManageRoute,
  PluginPluginIdRoute: PluginPluginIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
