import { Theme } from "@earendil-works/pi-coding-agent";

/** Semantic TUI colors use the Desktop terminal palette; default text/background stay native. */
export function createDesktopWidgetTheme(mode: "light" | "dark"): Theme {
  return new Theme(
    {
      accent: 4,
      border: 8,
      borderAccent: 4,
      borderMuted: 8,
      success: 2,
      error: 1,
      warning: 3,
      muted: 8,
      dim: 8,
      text: "",
      thinkingText: 8,
      userMessageText: "",
      customMessageText: "",
      customMessageLabel: 5,
      toolTitle: "",
      toolOutput: "",
      mdHeading: 4,
      mdLink: 4,
      mdLinkUrl: 8,
      mdCode: 2,
      mdCodeBlock: "",
      mdCodeBlockBorder: 8,
      mdQuote: 8,
      mdQuoteBorder: 8,
      mdHr: 8,
      mdListBullet: 4,
      toolDiffAdded: 2,
      toolDiffRemoved: 1,
      toolDiffContext: 8,
      syntaxComment: 8,
      syntaxKeyword: 5,
      syntaxFunction: 4,
      syntaxVariable: "",
      syntaxString: 2,
      syntaxNumber: 3,
      syntaxType: 6,
      syntaxOperator: "",
      syntaxPunctuation: 8,
      thinkingOff: 8,
      thinkingMinimal: 8,
      thinkingLow: 6,
      thinkingMedium: 4,
      thinkingHigh: 5,
      thinkingXhigh: 5,
      bashMode: 3,
    },
    {
      selectedBg: 8,
      userMessageBg: "",
      customMessageBg: "",
      toolPendingBg: "",
      toolSuccessBg: "",
      toolErrorBg: "",
    },
    "256color",
    { name: `desktop-${mode}` },
  );
}
