// @ts-nocheck -- Vendored upstream module; Desktop boundary behavior is covered by focused tests.
export {
	DEFAULT_FORK_PREAMBLE,
	wrapForkTask,
	type AcceptanceEvidenceKind,
	type AcceptanceInput,
	type AcceptanceLedger,
	type AcceptanceLevel,
	type AsyncStartedEvent,
	type ControlEvent,
	type Details,
	type ExecutionProjection,
	type JsonSchemaObject,
	type OutputMode,
	type ReviewProjection,
	type SingleResult,
	type SubagentResultStatus,
	type SubagentRunMode,
	type Usage,
} from "../shared/types.ts";
