/** Desktop IPC 频道名集中定义，避免 main 与 preload 漂移。 */
export const CHANNELS = {
	projectsList: "desktop:projects:list",
	projectsChoose: "desktop:projects:choose",
	projectsOpen: "desktop:projects:open",
	projectsRemove: "desktop:projects:remove",
	projectsActive: "desktop:projects:active",
	sessionsList: "desktop:sessions:list",
	sessionsCreate: "desktop:sessions:create",
	sessionsOpen: "desktop:sessions:open",
	sessionsRename: "desktop:sessions:rename",
	sessionsArchive: "desktop:sessions:archive",
	sessionsRemove: "desktop:sessions:remove",
	sessionsSend: "desktop:sessions:send",
	sessionsCancel: "desktop:sessions:cancel",
	sessionsClearQueue: "desktop:sessions:clear-queue",
	sessionsCompact: "desktop:sessions:compact",
	sessionsSetModel: "desktop:sessions:set-model",
	sessionsSetThinking: "desktop:sessions:set-thinking",
	sessionsRespond: "desktop:sessions:respond",
	sessionsSnapshot: "desktop:sessions:snapshot",
	filesList: "desktop:files:list",
	filesRead: "desktop:files:read",
	terminalsOpen: "desktop:terminals:open",
	terminalsWrite: "desktop:terminals:write",
	terminalsResize: "desktop:terminals:resize",
	terminalsRestart: "desktop:terminals:restart",
	terminalsEvent: "desktop:terminals:event",
	workbenchGet: "desktop:workbench:get",
	workbenchUpdate: "desktop:workbench:update",
} as const;
