/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatNewRouteImport } from './routes/_chat.new'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as SettingsArchivesRouteImport } from './routes/settings.archives'
import { Route as SettingsAuthRouteImport } from './routes/settings.auth'
import { Route as SettingsAutoTitleRouteImport } from './routes/settings.auto-title'
import { Route as SettingsDependenciesRouteImport } from './routes/settings.dependencies'
import { Route as SettingsExtensionsRouteImport } from './routes/settings.extensions'
import { Route as SettingsMemoryRouteImport } from './routes/settings.memory'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsPersonalizationRouteImport } from './routes/settings.personalization'
import { Route as SettingsSubagentsRouteImport } from './routes/settings.subagents'
import { Route as ChatPluginsIndexRouteImport } from './routes/_chat.plugins.index'
import { Route as ChatPluginsPluginIdRouteImport } from './routes/_chat.plugins.$pluginId'
import { Route as ChatPluginsLocalPluginIdRouteImport } from './routes/_chat.plugins.local.$pluginId'
import { Route as ChatProjectsProjectIdSessionThreadIdRouteImport } from './routes/_chat.projects.$projectId.session.$threadId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivesRoute = SettingsArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutoTitleRoute = SettingsAutoTitleRouteImport.update({
  id: '/auto-title',
  path: '/auto-title',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDependenciesRoute = SettingsDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPersonalizationRoute = SettingsPersonalizationRouteImport.update({
  id: '/personalization',
  path: '/personalization',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSubagentsRoute = SettingsSubagentsRouteImport.update({
  id: '/subagents',
  path: '/subagents',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatPluginsIndexRoute = ChatPluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatPluginsRoute,
} as any)
const ChatPluginsPluginIdRoute = ChatPluginsPluginIdRouteImport.update({
  id: '/$pluginId',
  path: '/$pluginId',
  getParentRoute: () => ChatPluginsRoute,
} as any)
const ChatPluginsLocalPluginIdRoute =
  ChatPluginsLocalPluginIdRouteImport.update({
    id: '/local/$pluginId',
    path: '/local/$pluginId',
    getParentRoute: () => ChatPluginsRoute,
  } as any)
const ChatProjectsProjectIdSessionThreadIdRoute =
  ChatProjectsProjectIdSessionThreadIdRouteImport.update({
    id: '/projects/$projectId/session/$threadId',
    path: '/projects/$projectId/session/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/new': typeof ChatNewRoute
  '/plugins': typeof ChatPluginsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/archives': typeof SettingsArchivesRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/auto-title': typeof SettingsAutoTitleRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/subagents': typeof SettingsSubagentsRoute
  '/settings/': typeof SettingsIndexRoute
  '/plugins/$pluginId': typeof ChatPluginsPluginIdRoute
  '/plugins/': typeof ChatPluginsIndexRoute
  '/plugins/local/$pluginId': typeof ChatPluginsLocalPluginIdRoute
  '/projects/$projectId/session/$threadId': typeof ChatProjectsProjectIdSessionThreadIdRoute
}
export interface FileRoutesByTo {
  '/new': typeof ChatNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/archives': typeof SettingsArchivesRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/auto-title': typeof SettingsAutoTitleRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/subagents': typeof SettingsSubagentsRoute
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/plugins/$pluginId': typeof ChatPluginsPluginIdRoute
  '/plugins': typeof ChatPluginsIndexRoute
  '/plugins/local/$pluginId': typeof ChatPluginsLocalPluginIdRoute
  '/projects/$projectId/session/$threadId': typeof ChatProjectsProjectIdSessionThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/new': typeof ChatNewRoute
  '/_chat/plugins': typeof ChatPluginsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/archives': typeof SettingsArchivesRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/auto-title': typeof SettingsAutoTitleRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/subagents': typeof SettingsSubagentsRoute
  '/_chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_chat/plugins/$pluginId': typeof ChatPluginsPluginIdRoute
  '/_chat/plugins/': typeof ChatPluginsIndexRoute
  '/_chat/plugins/local/$pluginId': typeof ChatPluginsLocalPluginIdRoute
  '/_chat/projects/$projectId/session/$threadId': typeof ChatProjectsProjectIdSessionThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/new'
    | '/plugins'
    | '/settings/about'
    | '/settings/archives'
    | '/settings/auth'
    | '/settings/auto-title'
    | '/settings/dependencies'
    | '/settings/extensions'
    | '/settings/memory'
    | '/settings/models'
    | '/settings/personalization'
    | '/settings/subagents'
    | '/settings/'
    | '/plugins/$pluginId'
    | '/plugins/'
    | '/plugins/local/$pluginId'
    | '/projects/$projectId/session/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/new'
    | '/settings/about'
    | '/settings/archives'
    | '/settings/auth'
    | '/settings/auto-title'
    | '/settings/dependencies'
    | '/settings/extensions'
    | '/settings/memory'
    | '/settings/models'
    | '/settings/personalization'
    | '/settings/subagents'
    | '/'
    | '/settings'
    | '/plugins/$pluginId'
    | '/plugins'
    | '/plugins/local/$pluginId'
    | '/projects/$projectId/session/$threadId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/new'
    | '/_chat/plugins'
    | '/settings/about'
    | '/settings/archives'
    | '/settings/auth'
    | '/settings/auto-title'
    | '/settings/dependencies'
    | '/settings/extensions'
    | '/settings/memory'
    | '/settings/models'
    | '/settings/personalization'
    | '/settings/subagents'
    | '/_chat/'
    | '/settings/'
    | '/_chat/plugins/$pluginId'
    | '/_chat/plugins/'
    | '/_chat/plugins/local/$pluginId'
    | '/_chat/projects/$projectId/session/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/new': {
      id: '/_chat/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archives': {
      id: '/settings/archives'
      path: '/archives'
      fullPath: '/settings/archives'
      preLoaderRoute: typeof SettingsArchivesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/auto-title': {
      id: '/settings/auto-title'
      path: '/auto-title'
      fullPath: '/settings/auto-title'
      preLoaderRoute: typeof SettingsAutoTitleRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dependencies': {
      id: '/settings/dependencies'
      path: '/dependencies'
      fullPath: '/settings/dependencies'
      preLoaderRoute: typeof SettingsDependenciesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/personalization': {
      id: '/settings/personalization'
      path: '/personalization'
      fullPath: '/settings/personalization'
      preLoaderRoute: typeof SettingsPersonalizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/subagents': {
      id: '/settings/subagents'
      path: '/subagents'
      fullPath: '/settings/subagents'
      preLoaderRoute: typeof SettingsSubagentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/plugins/': {
      id: '/_chat/plugins/'
      path: '/'
      fullPath: '/plugins/'
      preLoaderRoute: typeof ChatPluginsIndexRouteImport
      parentRoute: typeof ChatPluginsRoute
    }
    '/_chat/plugins/$pluginId': {
      id: '/_chat/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof ChatPluginsPluginIdRouteImport
      parentRoute: typeof ChatPluginsRoute
    }
    '/_chat/plugins/local/$pluginId': {
      id: '/_chat/plugins/local/$pluginId'
      path: '/local/$pluginId'
      fullPath: '/plugins/local/$pluginId'
      preLoaderRoute: typeof ChatPluginsLocalPluginIdRouteImport
      parentRoute: typeof ChatPluginsRoute
    }
    '/_chat/projects/$projectId/session/$threadId': {
      id: '/_chat/projects/$projectId/session/$threadId'
      path: '/projects/$projectId/session/$threadId'
      fullPath: '/projects/$projectId/session/$threadId'
      preLoaderRoute: typeof ChatProjectsProjectIdSessionThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatPluginsRouteChildren {
  ChatPluginsPluginIdRoute: typeof ChatPluginsPluginIdRoute
  ChatPluginsIndexRoute: typeof ChatPluginsIndexRoute
  ChatPluginsLocalPluginIdRoute: typeof ChatPluginsLocalPluginIdRoute
}

const ChatPluginsRouteChildren: ChatPluginsRouteChildren = {
  ChatPluginsPluginIdRoute: ChatPluginsPluginIdRoute,
  ChatPluginsIndexRoute: ChatPluginsIndexRoute,
  ChatPluginsLocalPluginIdRoute: ChatPluginsLocalPluginIdRoute,
}

const ChatPluginsRouteWithChildren = ChatPluginsRoute._addFileChildren(
  ChatPluginsRouteChildren,
)

interface ChatRouteChildren {
  ChatNewRoute: typeof ChatNewRoute
  ChatPluginsRoute: typeof ChatPluginsRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
  ChatProjectsProjectIdSessionThreadIdRoute: typeof ChatProjectsProjectIdSessionThreadIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatNewRoute: ChatNewRoute,
  ChatPluginsRoute: ChatPluginsRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
  ChatProjectsProjectIdSessionThreadIdRoute:
    ChatProjectsProjectIdSessionThreadIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsArchivesRoute: typeof SettingsArchivesRoute
  SettingsAuthRoute: typeof SettingsAuthRoute
  SettingsAutoTitleRoute: typeof SettingsAutoTitleRoute
  SettingsDependenciesRoute: typeof SettingsDependenciesRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsPersonalizationRoute: typeof SettingsPersonalizationRoute
  SettingsSubagentsRoute: typeof SettingsSubagentsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsArchivesRoute: SettingsArchivesRoute,
  SettingsAuthRoute: SettingsAuthRoute,
  SettingsAutoTitleRoute: SettingsAutoTitleRoute,
  SettingsDependenciesRoute: SettingsDependenciesRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsPersonalizationRoute: SettingsPersonalizationRoute,
  SettingsSubagentsRoute: SettingsSubagentsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
