/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAuthRouteImport } from './routes/settings.auth'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsPersonalizationRouteImport } from './routes/settings.personalization'
import { Route as ProjectsProjectIdSessionThreadIdRouteImport } from './routes/projects.$projectId.session.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPersonalizationRoute = SettingsPersonalizationRouteImport.update({
  id: '/personalization',
  path: '/personalization',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectIdSessionThreadIdRoute =
  ProjectsProjectIdSessionThreadIdRouteImport.update({
    id: '/projects/$projectId/session/$threadId',
    path: '/projects/$projectId/session/$threadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$projectId/session/$threadId': typeof ProjectsProjectIdSessionThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/$projectId/session/$threadId': typeof ProjectsProjectIdSessionThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$projectId/session/$threadId': typeof ProjectsProjectIdSessionThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/settings'
    | '/settings/auth'
    | '/settings/models'
    | '/settings/personalization'
    | '/settings/'
    | '/projects/$projectId/session/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/settings/auth'
    | '/settings/models'
    | '/settings/personalization'
    | '/settings'
    | '/projects/$projectId/session/$threadId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/settings'
    | '/settings/auth'
    | '/settings/models'
    | '/settings/personalization'
    | '/settings/'
    | '/projects/$projectId/session/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ProjectsProjectIdSessionThreadIdRoute: typeof ProjectsProjectIdSessionThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/personalization': {
      id: '/settings/personalization'
      path: '/personalization'
      fullPath: '/settings/personalization'
      preLoaderRoute: typeof SettingsPersonalizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectId/session/$threadId': {
      id: '/projects/$projectId/session/$threadId'
      path: '/projects/$projectId/session/$threadId'
      fullPath: '/projects/$projectId/session/$threadId'
      preLoaderRoute: typeof ProjectsProjectIdSessionThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAuthRoute: typeof SettingsAuthRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsPersonalizationRoute: typeof SettingsPersonalizationRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAuthRoute: SettingsAuthRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsPersonalizationRoute: SettingsPersonalizationRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ProjectsProjectIdSessionThreadIdRoute: ProjectsProjectIdSessionThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
