export type OfficeEngineErrorCode =
	| "ARCHIVE_TOO_LARGE"
	| "ARCHIVE_INVALID"
	| "ARCHIVE_LIMIT_INVALID"
	| "ARCHIVE_ENTRY_LIMIT"
	| "ARCHIVE_SINGLE_SIZE_LIMIT"
	| "ARCHIVE_TOTAL_SIZE_LIMIT"
	| "ARCHIVE_COMPRESSION_RATIO_LIMIT"
	| "ARCHIVE_PATH_TOO_LONG"
	| "ARCHIVE_UNSAFE_PATH"
	| "ARCHIVE_DUPLICATE_PATH"
	| "ZIP_MULTI_DISK"
	| "ZIP64_UNSUPPORTED"
	| "ZIP_ENCRYPTED"
	| "ZIP_DATA_DESCRIPTOR"
	| "ZIP_UNSUPPORTED_COMPRESSION"
	| "ZIP_FILENAME_ENCODING_UNSUPPORTED"
	| "ZIP_UNICODE_PATH_UNSUPPORTED"
	| "ZIP_CENTRAL_DIRECTORY_INVALID"
	| "ZIP_LOCAL_HEADER_INVALID"
	| "ZIP_LOCAL_CENTRAL_MISMATCH"
	| "ZIP_ENTRY_RANGE_INVALID"
	| "ZIP_ENTRY_OVERLAP"
	| "ZIP_CRC_MISMATCH"
	| "ZIP_DECOMPRESSION_FAILED"
	| "ZIP_FLAGS_INVALID"
	| "ZIP_VERSION_INVALID"
	| "ZIP_CENTRAL_DIRECTORY_TRAILING_DATA"
	| "XML_TOO_LARGE"
	| "XML_INVALID"
	| "XML_DTD_FORBIDDEN"
	| "XML_ENTITY_FORBIDDEN"
	| "XML_PI_FORBIDDEN"
	| "DOCX_MISSING_CONTENT_TYPES"
	| "DOCX_CONTENT_TYPE_INVALID"
	| "DOCX_MISSING_ROOT_RELATIONSHIPS"
	| "DOCX_RELATIONSHIP_INVALID"
	| "DOCX_EXTERNAL_RELATIONSHIP"
	| "DOCX_MISSING_OFFICE_DOCUMENT"
	| "DOCX_DUPLICATE_OFFICE_DOCUMENT"
	| "DOCX_TARGET_INVALID"
	| "DOCX_MAIN_PART_MISSING"
	| "DOCX_MAIN_CONTENT_TYPE_INVALID"
	| "DOCX_DOCUMENT_INVALID"
	| "DOCX_DOCUMENT_UNSAFE"
	| "VALIDATION_FAILED"
	| "TARGET_NOT_FOUND"
	| "OPERATION_BLOCKED"
	| "PRECONDITION_FAILED";

export class OfficeEngineError extends Error {
	readonly code: OfficeEngineErrorCode;

	constructor(code: OfficeEngineErrorCode, message?: string) {
		super(message ?? code);
		this.name = "OfficeEngineError";
		this.code = code;
	}
}

export function officeError(code: OfficeEngineErrorCode): OfficeEngineError {
	return new OfficeEngineError(code);
}
