export {
	type ArchiveLimits,
	DEFAULT_ARCHIVE_LIMITS,
	normalizeOpcPath,
	PackageArchive,
	type PackageArchiveEntry,
	verifyReplacement,
} from "./archive.ts";
export {
	CONTENT_TYPES_NAMESPACE,
	type DocxMainPart,
	type DocxPackageResolution,
	type DocxPartWarning,
	type DocxRelatedPart,
	resolveDocx,
	resolveDocxMainPart,
	STRICT_OFFICE_DOCUMENT_RELATIONSHIP,
	TRANSITIONAL_OFFICE_DOCUMENT_RELATIONSHIP,
	TRANSITIONAL_PACKAGE_RELATIONSHIPS_NAMESPACE,
	WORDPROCESSINGML_DOCUMENT_CONTENT_TYPE,
} from "./docx.ts";
export { OfficeEngineError, type OfficeEngineErrorCode, officeError } from "./errors.ts";
export type {
	CommentSnapshot,
	CommentsPartSnapshot,
	RelatedPartBlockedReason,
	RelatedPartKind,
	RelatedPartParagraphSnapshot,
	RelatedPartRunSnapshot,
	RelatedPartSnapshot,
} from "./related-parts.ts";
export {
	commitDocx,
	type DeleteParagraphOperation,
	type DocumentOperation,
	type DocumentOperationEnvelope,
	type DocumentPlan,
	type DocumentSemanticDiff,
	type DocxBlockedReason,
	type DocxInspectSnapshot,
	type DocxParagraphSnapshot,
	type DocxTextRunSnapshot,
	type InsertParagraphAfterOperation,
	inspectDocx,
	planDocx,
	type ReplaceCommentTextRunOperation,
	type ReplaceRelatedTextRunOperation,
	type ReplaceTextRangeOperation,
	type ReplaceTextRunOperation,
	type SetTextRunStyleOperation,
	sha256Hex,
	TRANSACTION_BUDGETS,
	validateDocumentOperationEnvelope,
} from "./transaction.ts";
export {
	commitXlsx,
	inspectXlsx,
	planXlsx,
	type SetCellValueOperation,
	validateXlsxOperationEnvelope,
	type XlsxCellSnapshot,
	type XlsxInspectSnapshot,
	type XlsxOperationEnvelope,
	type XlsxPlan,
	type XlsxSemanticDiff,
	type XlsxSheetSnapshot,
} from "./xlsx.ts";
